name: Update from Google Sheets

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        pip install pandas openpyxl gspread oauth2client

    - name: Set up Google Sheets credentials
      run: |
        echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > data_sources/google_sheets_api/service_account_JN.json

    - name: Fetch data and build website
      run: |
        python build_from_google_sheets.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add docs/data_catalog.xlsx docs/index.html
        git commit -m "Update data from Google Sheets" || echo "No changes to commit"
        git push 