name: Update Website from Google Sheets

on:
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: feature/new-dataset  # Use the new branch

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        pip install pandas openpyxl markdown gspread oauth2client

    - name: Set up Google Sheets credentials
      run: |
        echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > data_sources/google_sheets_api/service_account_JN.json

    - name: Fetch data from Google Sheets
      run: |
        python fetch_google_sheet.py --output docs/data_catalog.xlsx

    - name: Generate HTML
      run: |
        python generate_catalog.py --input docs/data_catalog.xlsx --output docs/index.html

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add --all  # Add all changes, including new untracked files
        git commit -m "Update website from Google Sheets" || echo "No changes to commit"
        git push origin feature/new-dataset

    - name: Check GitHub Pages status
      run: |
        echo "Checking GitHub Pages build status..."
        curl -s "https://api.github.com/repos/${{ github.repository }}/pages/builds/latest" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" 